<template>
    <div class="mt-3">
        Please select the appropriate input format for your data from the options provided in the dropdown menu. We now support both peptide and protein inputs. 
        You can either provide a raw list of peptides or proteins or use the output generated by some popular search engines.

        <v-select
            class="mt-3 mb-n5"
            v-model="inputFormat"
            label="Select your input format"
            density="comfortable"
            variant="outlined"
            :items="inputFormats"
            @update:model-value="e => $emit('update:model-value', e)"
        />
    </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import FileFormat from '../FileFormat';

export interface Props {
    modelValue: FileFormat;
}

const props = defineProps<Props>();

defineEmits(['update:model-value']);

const inputFormat = ref<FileFormat>(props.modelValue);

const inputFormats = [
    FileFormat.PEPTIDE_LIST,
    FileFormat.PEPTIDE_SHAKER,
    FileFormat.MAX_QUANT,
    FileFormat.PROTEOME_DISCOVERER,
    FileFormat.META_PROTEOME_ANALYZER,
    
    FileFormat.PROTEIN_LIST,
];

watch(() => props.modelValue, (newVal: FileFormat) => {
    inputFormat.value = newVal;
});
</script>

<style scoped>
.list-item:hover {
    background-color: red;
}
</style>
