import { describe, expect, it } from 'vitest';

// CompoundMap.ts exports a singleton, constructed at import time from config.
// With the fixture env set up in vitest.config.ts, importing it builds the
// map from backend/.fixture/, generated by globalSetup before this file is
// ever loaded.
import compoundMap from '../src/mappings/CompoundMap';

describe('CompoundMap', () => {
    it('reads names from the compound entity table, split on ; and trimmed', () => {
        const entry = compoundMap.get('C00001');

        expect(entry?.names).toEqual(['H2O', 'Water']);
    });

    it('joins the pathway name in from the pathway table via compound2pathway', () => {
        // compound2pathway only carries the compound id and the pathway id;
        // the name has to come from a separate lookup into the pathway map.
        // A wrong mapping would silently drop or blank this join.
        const entry = compoundMap.get('C00022');

        expect(entry?.pathways).toEqual([{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }]);
    });

    it('joins the module name in from the module table via compound2module', () => {
        // Same as above, but for compound2module. C00022 is the fixture's
        // real link; C00267 in the same file is a genuine dangling reference
        // covered separately by mappingLogs.test.ts.
        const entry = compoundMap.get('C00022');

        expect(entry?.modules).toEqual([{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }]);
    });

    it('links EC numbers via ec2compound', () => {
        const entry = compoundMap.get('C00001');

        expect(entry?.ecNumbers).toEqual(['1.1.1.1']);
    });

    it('links reaction ids via reaction2compound', () => {
        const entry = compoundMap.get('C00001');

        expect(entry?.reactionIds).toEqual(['R00623']);
    });

    it('leaves pathways and modules empty when there is no link table entry', () => {
        const entry = compoundMap.get('C00001');

        expect(entry?.pathways).toEqual([]);
        expect(entry?.modules).toEqual([]);
    });

    it('builds the full entry for C00001', () => {
        expect(compoundMap.get('C00001')).toEqual({
            names: ['H2O', 'Water'],
            pathways: [],
            modules: [],
            ecNumbers: ['1.1.1.1'],
            reactionIds: ['R00623'],
        });
    });

    it('builds the full entry for C00022 (pyruvate)', () => {
        // Covers the non-empty modules case: C00001 has none, C00022 has one.
        expect(compoundMap.get('C00022')).toEqual({
            names: ['Pyruvate'],
            pathways: [{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }],
            modules: [{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }],
            ecNumbers: [],
            reactionIds: [],
        });
    });

    it('returns undefined for an unknown key', () => {
        expect(compoundMap.get('C99999')).toBeUndefined();
    });
});
