import { describe, expect, it } from 'vitest';

// KoMap.ts exports a singleton, constructed at import time from config.
// With the fixture env set up in vitest.config.ts, importing it builds the
// map from backend/.fixture/, generated by globalSetup before this file is
// ever loaded.
import koMap from '../src/mappings/KoMap';

describe('KoMap', () => {
    it('reads names from the ko entity table, dropping the symbol segment and the [EC:...] suffix', () => {
        // "K00001\tE1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]" splits
        // on ';' into the symbol segment and the description; only the
        // description is kept as a name, with the trailing EC suffix
        // stripped off.
        const entry = koMap.get('K00001');

        expect(entry?.names).toEqual(['alcohol dehydrogenase']);
    });

    it('parses EC numbers out of the [EC:...] suffix of the description', () => {
        // Real parsing logic unique to KoMap: descriptionEcRegex pulls the
        // EC number(s) out of the entity table line itself, independent of
        // the ec2ko link table.
        const entry = koMap.get('K00844');

        expect(entry?.ecNumbers).toEqual(['2.7.1.1']);
    });

    it('joins the pathway name in from the pathway table via ko2pathway', () => {
        // ko2pathway only carries the KO number and the pathway id; the name
        // has to come from a separate lookup into the pathway map. A wrong
        // mapping would silently drop or blank this join.
        const entry = koMap.get('K00001');

        expect(entry?.pathways).toEqual([{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }]);
    });

    it('joins the module name in from the module table via ko2module', () => {
        const entry = koMap.get('K00844');

        expect(entry?.modules).toEqual([{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }]);
    });

    it('links reaction ids via ko2reaction', () => {
        const entry = koMap.get('K00001');

        expect(entry?.reactionIds).toEqual(['R00623']);
    });

    it('leaves modules empty when there is no ko2module entry', () => {
        const entry = koMap.get('K00001');

        expect(entry?.modules).toEqual([]);
    });

    it('leaves pathways and reactionIds empty when there is no matching link table entry', () => {
        const entry = koMap.get('K00844');

        expect(entry?.pathways).toEqual([]);
        expect(entry?.reactionIds).toEqual([]);
    });

    it('builds the full entry for K00001 (alcohol dehydrogenase)', () => {
        expect(koMap.get('K00001')).toEqual({
            names: ['alcohol dehydrogenase'],
            pathways: [{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }],
            modules: [],
            ecNumbers: ['1.1.1.1'],
            reactionIds: ['R00623'],
        });
    });

    it('builds the full entry for K00844 (hexokinase)', () => {
        // Covers the non-empty modules case: K00001 has none, K00844 has one.
        expect(koMap.get('K00844')).toEqual({
            names: ['hexokinase'],
            pathways: [],
            modules: [{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }],
            ecNumbers: ['2.7.1.1'],
            reactionIds: [],
        });
    });

    it('returns undefined for an unknown key', () => {
        expect(koMap.get('K99999')).toBeUndefined();
    });
});
