import { describe, expect, it } from 'vitest';

// ReactionMap.ts exports a singleton, constructed at import time from
// config. With the fixture env set up in vitest.config.ts, importing it
// builds the map from backend/.fixture/, generated by globalSetup before
// this file is ever loaded.
import reactionMap from '../src/mappings/ReactionMap';

describe('ReactionMap', () => {
    it('reads names from the reaction entity table, split on ; and trimmed', () => {
        const entry = reactionMap.get('R00623');

        expect(entry?.names).toEqual(['alcohol dehydrogenase reaction', 'aldehyde reductase reaction']);
    });

    it('joins the pathway name in from the pathway table via reaction2pathway', () => {
        // reaction2pathway only carries the reaction id and the pathway id;
        // the name has to come from a separate lookup into the pathway map.
        // A wrong mapping would silently drop or blank this join.
        const entry = reactionMap.get('R00623');

        expect(entry?.pathways).toEqual([{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }]);
    });

    it('joins the module name in from the module table via reaction2module', () => {
        const entry = reactionMap.get('R00299');

        expect(entry?.modules).toEqual([{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }]);
    });

    it('links EC numbers via ec2reaction', () => {
        const entry = reactionMap.get('R00623');

        expect(entry?.ecNumbers).toEqual(['1.1.1.1']);
    });

    it('leaves modules empty when there is no reaction2module entry', () => {
        const entry = reactionMap.get('R00623');

        expect(entry?.modules).toEqual([]);
    });

    it('leaves pathways empty when there is no reaction2pathway entry', () => {
        const entry = reactionMap.get('R00299');

        expect(entry?.pathways).toEqual([]);
    });

    it('builds the full entry for R00623 (alcohol dehydrogenase reaction)', () => {
        expect(reactionMap.get('R00623')).toEqual({
            names: ['alcohol dehydrogenase reaction', 'aldehyde reductase reaction'],
            pathways: [{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }],
            modules: [],
            ecNumbers: ['1.1.1.1'],
        });
    });

    it('builds the full entry for R00299 (hexokinase reaction)', () => {
        // Covers the non-empty modules case: R00623 has none, R00299 has one.
        expect(reactionMap.get('R00299')).toEqual({
            names: ['hexokinase reaction'],
            pathways: [],
            modules: [{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }],
            ecNumbers: ['2.7.1.1'],
        });
    });

    it('returns undefined for an unknown key', () => {
        expect(reactionMap.get('R99999')).toBeUndefined();
    });
});
