export default new Map(Object.entries({
    'map01100': [ 'Metabolism', 'Global and overview maps' ],
    'map01110': [ 'Metabolism', 'Global and overview maps' ],
    'map01120': [ 'Metabolism', 'Global and overview maps' ],
    'map01200': [ 'Metabolism', 'Global and overview maps' ],
    'map01210': [ 'Metabolism', 'Global and overview maps' ],
    'map01212': [ 'Metabolism', 'Global and overview maps' ],
    'map01230': [ 'Metabolism', 'Global and overview maps' ],
    'map01232': [ 'Metabolism', 'Global and overview maps' ],
    'map01250': [ 'Metabolism', 'Global and overview maps' ],
    'map01240': [ 'Metabolism', 'Global and overview maps' ],
    'map01220': [ 'Metabolism', 'Global and overview maps' ],

    'map00010': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00020': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00030': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00040': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00051': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00052': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00053': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00500': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00520': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00620': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00630': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00640': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00650': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00660': [ 'Metabolism', 'Carbohydrate metabolism' ],
    'map00562': [ 'Metabolism', 'Carbohydrate metabolism' ],

    'map00190': [ 'Metabolism', 'Energy metabolism' ],
    'map00195': [ 'Metabolism', 'Energy metabolism' ],
    'map00196': [ 'Metabolism', 'Energy metabolism' ],
    'map00710': [ 'Metabolism', 'Energy metabolism' ],
    'map00720': [ 'Metabolism', 'Energy metabolism' ],
    'map00680': [ 'Metabolism', 'Energy metabolism' ],
    'map00910': [ 'Metabolism', 'Energy metabolism' ],
    'map00920': [ 'Metabolism', 'Energy metabolism' ],

    'map00061': [ 'Metabolism', 'Lipid metabolism' ],
    'map00062': [ 'Metabolism', 'Lipid metabolism' ],
    'map00071': [ 'Metabolism', 'Lipid metabolism' ],
    'map00073': [ 'Metabolism', 'Lipid metabolism' ],
    'map00100': [ 'Metabolism', 'Lipid metabolism' ],
    'map00120': [ 'Metabolism', 'Lipid metabolism' ],
    'map00121': [ 'Metabolism', 'Lipid metabolism' ],
    'map00140': [ 'Metabolism', 'Lipid metabolism' ],
    'map00561': [ 'Metabolism', 'Lipid metabolism' ],
    'map00564': [ 'Metabolism', 'Lipid metabolism' ],
    'map00565': [ 'Metabolism', 'Lipid metabolism' ],
    'map00600': [ 'Metabolism', 'Lipid metabolism' ],
    'map00590': [ 'Metabolism', 'Lipid metabolism' ],
    'map00591': [ 'Metabolism', 'Lipid metabolism' ],
    'map00592': [ 'Metabolism', 'Lipid metabolism' ],
    'map01040': [ 'Metabolism', 'Lipid metabolism' ],

    'map00230': [ 'Metabolism', 'Nucleotide metabolism' ],
    'map00240': [ 'Metabolism', 'Nucleotide metabolism' ],

    'map00250': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00260': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00270': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00280': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00290': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00300': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00310': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00220': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00330': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00340': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00350': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00360': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00380': [ 'Metabolism', 'Amino acid metabolism' ],
    'map00400': [ 'Metabolism', 'Amino acid metabolism' ],

    'map00410': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00430': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00440': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00450': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00460': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00470': [ 'Metabolism', 'Metabolism of other amino acids' ],
    'map00480': [ 'Metabolism', 'Metabolism of other amino acids' ],

    'map00510': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00513': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00512': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00515': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00514': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00532': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00534': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00533': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00531': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00563': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00601': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00603': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00604': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00511': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00540': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00542': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00541': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00550': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00552': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00571': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00572': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],
    'map00543': [ 'Metabolism', 'Glycan biosynthesis and metabolism' ],

    'map00730': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00740': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00750': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00760': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00770': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00780': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00785': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00790': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00670': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00830': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00860': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],
    'map00130': [ 'Metabolism', 'Metabolism of cofactors and vitamins' ],

    'map00900': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00902': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00909': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00904': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00906': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00905': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00981': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00908': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00903': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00907': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01052': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00522': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01051': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01059': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01056': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01057': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00253': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map00523': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01054': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01053': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],
    'map01055': [ 'Metabolism', 'Metabolism of terpenoids and polyketides' ],

    'map00940': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00945': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00941': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00944': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00942': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00943': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00946': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00901': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00403': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00950': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00960': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00996': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00232': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00965': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00966': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00402': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00311': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00332': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00261': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00331': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00521': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00524': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00525': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00401': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00404': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00405': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00333': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00254': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00998': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00999': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],
    'map00997': [ 'Metabolism', 'Biosynthesis of other secondary metabolites' ],

    'map00362': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00627': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00364': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00625': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00361': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00623': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00622': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00633': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00642': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00643': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00791': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00930': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00363': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00621': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00626': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00624': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00365': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00984': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00980': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00982': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],
    'map00983': [ 'Metabolism', 'Xenobiotics biodegradation and metabolism' ],

    'map01010': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01060': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01061': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01062': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01063': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01064': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01065': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01066': [ 'Metabolism', 'Chemical structure transformation maps' ],
    'map01070': [ 'Metabolism', 'Chemical structure transformation maps' ],

    'map03020': [ 'Genetic Information Processing', 'Transcription' ],
    'map03022': [ 'Genetic Information Processing', 'Transcription' ],
    'map03040': [ 'Genetic Information Processing', 'Transcription' ],

    'map03010': [ 'Genetic Information Processing', 'Translation' ],
    'map00970': [ 'Genetic Information Processing', 'Translation' ],
    'map03013': [ 'Genetic Information Processing', 'Translation' ],
    'map03015': [ 'Genetic Information Processing', 'Translation' ],
    'map03008': [ 'Genetic Information Processing', 'Translation' ],

    'map03060': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map04141': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map04130': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map04120': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map04122': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map03050': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],
    'map03018': [ 'Genetic Information Processing', 'Folding, sorting and degradation' ],

    'map03030': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03410': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03420': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03430': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03440': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03450': [ 'Genetic Information Processing', 'Replication and repair' ],
    'map03460': [ 'Genetic Information Processing', 'Replication and repair' ],

    'map03230': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03240': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03250': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03260': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03262': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03261': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03263': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03264': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03265': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03266': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03268': [ 'Genetic Information Processing', 'Information processing in viruses' ],
    'map03267': [ 'Genetic Information Processing', 'Information processing in viruses' ],

    'map02010': [ 'Environmental Information Processing', 'Membrane transport' ],
    'map02060': [ 'Environmental Information Processing', 'Membrane transport' ],
    'map03070': [ 'Environmental Information Processing', 'Membrane transport' ],

    'map02020': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04010': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04013': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04016': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04011': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04012': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04014': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04015': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04310': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04330': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04340': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04341': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04350': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04390': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04391': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04392': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04370': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04371': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04630': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04064': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04668': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04066': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04068': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04020': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04070': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04072': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04071': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04024': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04022': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04151': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04152': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04150': [ 'Environmental Information Processing', 'Signal transduction' ],
    'map04075': [ 'Environmental Information Processing', 'Signal transduction' ],

    'map04080': [ 'Environmental Information Processing', 'Signaling molecules and interaction' ],
    'map04060': [ 'Environmental Information Processing', 'Signaling molecules and interaction' ],
    'map04061': [ 'Environmental Information Processing', 'Signaling molecules and interaction' ],
    'map04512': [ 'Environmental Information Processing', 'Signaling molecules and interaction' ],
    'map04514': [ 'Environmental Information Processing', 'Signaling molecules and interaction' ],

    'map04144': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04145': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04142': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04146': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04140': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04138': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04136': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04137': [ 'Cellular Processes', 'Transport and catabolism' ],
    'map04139': [ 'Cellular Processes', 'Transport and catabolism' ],

    'map04110': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04111': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04112': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04113': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04114': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04210': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04214': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04215': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04216': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04217': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04115': [ 'Cellular Processes', 'Cell growth and death' ],
    'map04218': [ 'Cellular Processes', 'Cell growth and death' ],

    'map04510': [ 'Cellular Processes', 'Cellular community - eukaryotes' ],
    'map04520': [ 'Cellular Processes', 'Cellular community - eukaryotes' ],
    'map04530': [ 'Cellular Processes', 'Cellular community - eukaryotes' ],
    'map04540': [ 'Cellular Processes', 'Cellular community - eukaryotes' ],
    'map04550': [ 'Cellular Processes', 'Cellular community - eukaryotes' ],

    'map02024': [ 'Cellular Processes', 'Cellular community - prokaryotes' ],
    'map05111': [ 'Cellular Processes', 'Cellular community - prokaryotes' ],
    'map02025': [ 'Cellular Processes', 'Cellular community - prokaryotes' ],
    'map02026': [ 'Cellular Processes', 'Cellular community - prokaryotes' ],

    'map02030': [ 'Cellular Processes', 'Cell motility' ],
    'map02040': [ 'Cellular Processes', 'Cell motility' ],
    'map04814': [ 'Cellular Processes', 'Cell motility' ],
    'map04810': [ 'Cellular Processes', 'Cell motility' ],

    'map04640': [ 'Organismal Systems', 'Immune system' ],
    'map04610': [ 'Organismal Systems', 'Immune system' ],
    'map04611': [ 'Organismal Systems', 'Immune system' ],
    'map04613': [ 'Organismal Systems', 'Immune system' ],
    'map04620': [ 'Organismal Systems', 'Immune system' ],
    'map04624': [ 'Organismal Systems', 'Immune system' ],
    'map04621': [ 'Organismal Systems', 'Immune system' ],
    'map04622': [ 'Organismal Systems', 'Immune system' ],
    'map04623': [ 'Organismal Systems', 'Immune system' ],
    'map04625': [ 'Organismal Systems', 'Immune system' ],
    'map04650': [ 'Organismal Systems', 'Immune system' ],
    'map04612': [ 'Organismal Systems', 'Immune system' ],
    'map04660': [ 'Organismal Systems', 'Immune system' ],
    'map04658': [ 'Organismal Systems', 'Immune system' ],
    'map04659': [ 'Organismal Systems', 'Immune system' ],
    'map04657': [ 'Organismal Systems', 'Immune system' ],
    'map04662': [ 'Organismal Systems', 'Immune system' ],
    'map04664': [ 'Organismal Systems', 'Immune system' ],
    'map04666': [ 'Organismal Systems', 'Immune system' ],
    'map04670': [ 'Organismal Systems', 'Immune system' ],
    'map04672': [ 'Organismal Systems', 'Immune system' ],
    'map04062': [ 'Organismal Systems', 'Immune system' ],

    'map04911': [ 'Organismal Systems', 'Endocrine system' ],
    'map04910': [ 'Organismal Systems', 'Endocrine system' ],
    'map04922': [ 'Organismal Systems', 'Endocrine system' ],
    'map04923': [ 'Organismal Systems', 'Endocrine system' ],
    'map04920': [ 'Organismal Systems', 'Endocrine system' ],
    'map03320': [ 'Organismal Systems', 'Endocrine system' ],
    'map04929': [ 'Organismal Systems', 'Endocrine system' ],
    'map04912': [ 'Organismal Systems', 'Endocrine system' ],
    'map04913': [ 'Organismal Systems', 'Endocrine system' ],
    'map04915': [ 'Organismal Systems', 'Endocrine system' ],
    'map04914': [ 'Organismal Systems', 'Endocrine system' ],
    'map04917': [ 'Organismal Systems', 'Endocrine system' ],
    'map04921': [ 'Organismal Systems', 'Endocrine system' ],
    'map04926': [ 'Organismal Systems', 'Endocrine system' ],
    'map04935': [ 'Organismal Systems', 'Endocrine system' ],
    'map04918': [ 'Organismal Systems', 'Endocrine system' ],
    'map04919': [ 'Organismal Systems', 'Endocrine system' ],
    'map04928': [ 'Organismal Systems', 'Endocrine system' ],
    'map04916': [ 'Organismal Systems', 'Endocrine system' ],
    'map04924': [ 'Organismal Systems', 'Endocrine system' ],
    'map04614': [ 'Organismal Systems', 'Endocrine system' ],
    'map04925': [ 'Organismal Systems', 'Endocrine system' ],
    'map04927': [ 'Organismal Systems', 'Endocrine system' ],

    'map04260': [ 'Organismal Systems', 'Circulatory system' ],
    'map04261': [ 'Organismal Systems', 'Circulatory system' ],
    'map04270': [ 'Organismal Systems', 'Circulatory system' ],

    'map04970': [ 'Organismal Systems', 'Digestive system' ],
    'map04971': [ 'Organismal Systems', 'Digestive system' ],
    'map04972': [ 'Organismal Systems', 'Digestive system' ],
    'map04976': [ 'Organismal Systems', 'Digestive system' ],
    'map04973': [ 'Organismal Systems', 'Digestive system' ],
    'map04974': [ 'Organismal Systems', 'Digestive system' ],
    'map04975': [ 'Organismal Systems', 'Digestive system' ],
    'map04979': [ 'Organismal Systems', 'Digestive system' ],
    'map04977': [ 'Organismal Systems', 'Digestive system' ],
    'map04978': [ 'Organismal Systems', 'Digestive system' ],

    'map04962': [ 'Organismal Systems', 'Excretory system' ],
    'map04960': [ 'Organismal Systems', 'Excretory system' ],
    'map04961': [ 'Organismal Systems', 'Excretory system' ],
    'map04964': [ 'Organismal Systems', 'Excretory system' ],
    'map04966': [ 'Organismal Systems', 'Excretory system' ],

    'map04724': [ 'Organismal Systems', 'Nervous system' ],
    'map04727': [ 'Organismal Systems', 'Nervous system' ],
    'map04725': [ 'Organismal Systems', 'Nervous system' ],
    'map04728': [ 'Organismal Systems', 'Nervous system' ],
    'map04726': [ 'Organismal Systems', 'Nervous system' ],
    'map04720': [ 'Organismal Systems', 'Nervous system' ],
    'map04730': [ 'Organismal Systems', 'Nervous system' ],
    'map04723': [ 'Organismal Systems', 'Nervous system' ],
    'map04721': [ 'Organismal Systems', 'Nervous system' ],
    'map04722': [ 'Organismal Systems', 'Nervous system' ],

    'map04744': [ 'Organismal Systems', 'Sensory system' ],
    'map04745': [ 'Organismal Systems', 'Sensory system' ],
    'map04740': [ 'Organismal Systems', 'Sensory system' ],
    'map04742': [ 'Organismal Systems', 'Sensory system' ],
    'map04750': [ 'Organismal Systems', 'Sensory system' ],

    'map04320': [ 'Organismal Systems', 'Development and regeneration' ],
    'map04360': [ 'Organismal Systems', 'Development and regeneration' ],
    'map04361': [ 'Organismal Systems', 'Development and regeneration' ],
    'map04380': [ 'Organismal Systems', 'Development and regeneration' ],

    'map04211': [ 'Organismal Systems', 'Aging' ],
    'map04212': [ 'Organismal Systems', 'Aging' ],
    'map04213': [ 'Organismal Systems', 'Aging' ],

    'map04710': [ 'Organismal Systems', 'Environmental adaptation' ],
    'map04713': [ 'Organismal Systems', 'Environmental adaptation' ],
    'map04711': [ 'Organismal Systems', 'Environmental adaptation' ],
    'map04712': [ 'Organismal Systems', 'Environmental adaptation' ],
    'map04714': [ 'Organismal Systems', 'Environmental adaptation' ],
    'map04626': [ 'Organismal Systems', 'Environmental adaptation' ],

    'map05200': [ 'Human Diseases', 'Cancer: overview' ],
    'map05202': [ 'Human Diseases', 'Cancer: overview' ],
    'map05206': [ 'Human Diseases', 'Cancer: overview' ],
    'map05205': [ 'Human Diseases', 'Cancer: overview' ],
    'map05204': [ 'Human Diseases', 'Cancer: overview' ],
    'map05207': [ 'Human Diseases', 'Cancer: overview' ],
    'map05208': [ 'Human Diseases', 'Cancer: overview' ],
    'map05203': [ 'Human Diseases', 'Cancer: overview' ],
    'map05230': [ 'Human Diseases', 'Cancer: overview' ],
    'map05231': [ 'Human Diseases', 'Cancer: overview' ],
    'map05235': [ 'Human Diseases', 'Cancer: overview' ],

    'map05210': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05212': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05225': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05226': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05214': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05216': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05221': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05220': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05217': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05218': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05211': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05219': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05215': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05213': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05224': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05222': [ 'Human Diseases', 'Cancer: specific types' ],
    'map05223': [ 'Human Diseases', 'Cancer: specific types' ],

    'map05166': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05170': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05161': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05160': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05171': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05164': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05162': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05168': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05163': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05167': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05169': [ 'Human Diseases', 'Infectious disease: viral' ],
    'map05165': [ 'Human Diseases', 'Infectious disease: viral' ],

    'map05110': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05120': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05130': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05132': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05131': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05135': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05133': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05134': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05150': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05152': [ 'Human Diseases', 'Infectious disease: bacterial' ],
    'map05100': [ 'Human Diseases', 'Infectious disease: bacterial' ],

    'map05146': [ 'Human Diseases', 'Infectious disease: parasitic' ],
    'map05144': [ 'Human Diseases', 'Infectious disease: parasitic' ],
    'map05145': [ 'Human Diseases', 'Infectious disease: parasitic' ],
    'map05140': [ 'Human Diseases', 'Infectious disease: parasitic' ],
    'map05142': [ 'Human Diseases', 'Infectious disease: parasitic' ],
    'map05143': [ 'Human Diseases', 'Infectious disease: parasitic' ],

    'map05310': [ 'Human Diseases', 'Immune disease' ],
    'map05322': [ 'Human Diseases', 'Immune disease' ],
    'map05323': [ 'Human Diseases', 'Immune disease' ],
    'map05320': [ 'Human Diseases', 'Immune disease' ],
    'map05321': [ 'Human Diseases', 'Immune disease' ],
    'map05330': [ 'Human Diseases', 'Immune disease' ],
    'map05332': [ 'Human Diseases', 'Immune disease' ],
    'map05340': [ 'Human Diseases', 'Immune disease' ],

    'map05010': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05012': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05014': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05016': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05017': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05020': [ 'Human Diseases', 'Neurodegenerative disease' ],
    'map05022': [ 'Human Diseases', 'Neurodegenerative disease' ],

    'map05030': [ 'Human Diseases', 'Substance dependence' ],
    'map05031': [ 'Human Diseases', 'Substance dependence' ],
    'map05032': [ 'Human Diseases', 'Substance dependence' ],
    'map05033': [ 'Human Diseases', 'Substance dependence' ],
    'map05034': [ 'Human Diseases', 'Substance dependence' ],

    'map05417': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05418': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05410': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05412': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05414': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05415': [ 'Human Diseases', 'Cardiovascular disease' ],
    'map05416': [ 'Human Diseases', 'Cardiovascular disease' ],

    'map04930': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04940': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04950': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04936': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04932': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04931': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04933': [ 'Human Diseases', 'Endocrine and metabolic disease' ],
    'map04934': [ 'Human Diseases', 'Endocrine and metabolic disease' ],

    'map01501': [ 'Human Diseases', 'Drug resistance: antimicrobial' ],
    'map01502': [ 'Human Diseases', 'Drug resistance: antimicrobial' ],
    'map01503': [ 'Human Diseases', 'Drug resistance: antimicrobial' ],

    'map01521': [ 'Human Diseases', 'Drug resistance: antineoplastic' ],
    'map01524': [ 'Human Diseases', 'Drug resistance: antineoplastic' ],
    'map01523': [ 'Human Diseases', 'Drug resistance: antineoplastic' ],
    'map01522': [ 'Human Diseases', 'Drug resistance: antineoplastic' ],

    'map07011': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07012': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07013': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07021': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07019': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07020': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07014': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07023': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07026': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07044': [ 'Drug Development', 'Chronology: Antiinfectives' ],
    'map07053': [ 'Drug Development', 'Chronology: Antiinfectives' ],

    'map07040': [ 'Drug Development', 'Chronology: Antineoplastics' ],
    'map07041': [ 'Drug Development', 'Chronology: Antineoplastics' ],
    'map07042': [ 'Drug Development', 'Chronology: Antineoplastics' ],
    'map07043': [ 'Drug Development', 'Chronology: Antineoplastics' ],
    'map07045': [ 'Drug Development', 'Chronology: Antineoplastics' ],

    'map07032': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07030': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07033': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07015': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07039': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07028': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07029': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07031': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07027': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07056': [ 'Drug Development', 'Chronology: Nervous system agents' ],
    'map07057': [ 'Drug Development', 'Chronology: Nervous system agents' ],

    'map07055': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07016': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07017': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07018': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07037': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07038': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07046': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07047': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07048': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07049': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07050': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07051': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07052': [ 'Drug Development', 'Chronology: Other drugs' ],
    'map07054': [ 'Drug Development', 'Chronology: Other drugs' ],

    'map07220': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07215': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07214': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07213': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07212': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07227': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07211': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07228': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07224': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],
    'map07229': [ 'Drug Development', 'Target-based classification: G protein-coupled receptors' ],

    'map07225': [ 'Drug Development', 'Target-based classification: Nuclear receptors' ],
    'map07226': [ 'Drug Development', 'Target-based classification: Nuclear receptors' ],
    'map07223': [ 'Drug Development', 'Target-based classification: Nuclear receptors' ],
    'map07222': [ 'Drug Development', 'Target-based classification: Nuclear receptors' ],

    'map07221': [ 'Drug Development', 'Target-based classification: Ion channels' ],
    'map07230': [ 'Drug Development', 'Target-based classification: Ion channels' ],
    'map07036': [ 'Drug Development', 'Target-based classification: Ion channels' ],
    'map07231': [ 'Drug Development', 'Target-based classification: Ion channels' ],
    'map07232': [ 'Drug Development', 'Target-based classification: Ion channels' ],
    'map07235': [ 'Drug Development', 'Target-based classification: Ion channels' ],

    'map07233': [ 'Drug Development', 'Target-based classification: Transporters' ],
    'map07234': [ 'Drug Development', 'Target-based classification: Transporters' ],

    'map07216': [ 'Drug Development', 'Target-based classification: Enzymes' ],
    'map07219': [ 'Drug Development', 'Target-based classification: Enzymes' ],
    'map07024': [ 'Drug Development', 'Target-based classification: Enzymes' ],
    'map07217': [ 'Drug Development', 'Target-based classification: Enzymes' ],
    'map07218': [ 'Drug Development', 'Target-based classification: Enzymes' ],

    'map07025': [ 'Drug Development', 'Structure-based classification' ],
    'map07034': [ 'Drug Development', 'Structure-based classification' ],
    'map07035': [ 'Drug Development', 'Structure-based classification' ],

    'map07110': [ 'Drug Development', 'Skeleton-based classification' ],
    'map07112': [ 'Drug Development', 'Skeleton-based classification' ],
    'map07114': [ 'Drug Development', 'Skeleton-based classification' ],
    'map07117': [ 'Drug Development', 'Skeleton-based classification' ]
}));
