import { describe, expect, it } from 'vitest';

// EcMap.ts exports a singleton, constructed at import time from config.
// With the fixture env set up in vitest.config.ts, importing it builds the
// map from backend/.fixture/, generated by globalSetup before this file is
// ever loaded.
import ecMap from '../../src/mappings/EcMap';

describe('EcMap', () => {
    it('reads names from the ec entity table, split on ; and trimmed', () => {
        const entry = ecMap.get('1.1.1.1');

        expect(entry?.names).toEqual(['alcohol dehydrogenase', 'aldehyde reductase', 'ADH']);
    });

    it('joins the pathway name in from the pathway table via ec2pathway', () => {
        // ec2pathway only carries the ec number and the pathway id; the name
        // has to come from a separate lookup into the pathway map. A wrong
        // mapping would silently drop or blank this join.
        const entry = ecMap.get('1.1.1.1');

        expect(entry?.pathways).toEqual([{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }]);
    });

    it('links KO numbers via ec2ko', () => {
        const entry = ecMap.get('1.1.1.1');

        expect(entry?.koNumbers).toEqual(['K00001']);
    });

    it('links reaction ids via ec2reaction', () => {
        const entry = ecMap.get('1.1.1.1');

        expect(entry?.reactionIds).toEqual(['R00623']);
    });

    it('leaves modules empty when there is no ec2module entry', () => {
        const entry = ecMap.get('1.1.1.1');

        expect(entry?.modules).toEqual([]);
    });

    it('builds the full entry for 1.1.1.1', () => {
        expect(ecMap.get('1.1.1.1')).toEqual({
            names: ['alcohol dehydrogenase', 'aldehyde reductase', 'ADH'],
            pathways: [{ id: 'map00010', name: 'Glycolysis / Gluconeogenesis' }],
            modules: [],
            koNumbers: ['K00001'],
            reactionIds: ['R00623'],
        });
    });

    it('links a module via ec2module for 2.7.1.1 (hexokinase)', () => {
        // Covers the non-empty modules case: 1.1.1.1 has none, 2.7.1.1 has one.
        const entry = ecMap.get('2.7.1.1');

        expect(entry?.names).toEqual(['hexokinase', 'glucokinase']);
        expect(entry?.modules).toEqual([{ id: 'M00001', name: 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate' }]);
    });

    it('returns undefined for an unknown key', () => {
        expect(ecMap.get('9.9.9.9')).toBeUndefined();
    });
});
