import { describe, expect, it } from 'vitest';

// ModuleMap.ts exports a singleton, constructed at import time from config.
// With the fixture env set up in vitest.config.ts, importing it builds the
// map from backend/.fixture/, generated by globalSetup before this file is
// ever loaded.
import moduleMap from '../../src/mappings/ModuleMap';

describe('ModuleMap', () => {
    it('reads the name from the module entity table, trimmed', () => {
        const entry = moduleMap.get('M00001');

        expect(entry?.name).toEqual('Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate');
    });

    it('returns undefined for an unknown key', () => {
        expect(moduleMap.get('M99999')).toBeUndefined();
    });
});
