import { describe, expect, it } from 'vitest';

// PathwayMap.ts exports a singleton, constructed at import time from
// config. With the fixture env set up in vitest.config.ts, importing it
// builds the map from backend/.fixture/, generated by globalSetup before
// this file is ever loaded.
import pathwayMap from '../../src/mappings/PathwayMap';

describe('PathwayMap', () => {
    it('reads the name from the pathway entity table, trimmed', () => {
        const entry = pathwayMap.get('map00010');

        expect(entry?.name).toEqual('Glycolysis / Gluconeogenesis');
    });

    it('joins the category and subCategory in from CategoryMap', () => {
        // The pathway entity table only carries the id and its description;
        // category/subCategory come from a separate lookup into
        // pathway/CategoryMap. A wrong mapping would silently blank this join.
        const entry = pathwayMap.get('map00010');

        expect(entry?.category).toEqual('Metabolism');
        expect(entry?.subCategory).toEqual('Carbohydrate metabolism');
    });

    it('links EC numbers via ec2pathway', () => {
        const entry = pathwayMap.get('map00010');

        expect(entry?.ecNumbers).toEqual(['1.1.1.1', '2.7.1.1']);
    });

    it('links KO numbers via ko2pathway', () => {
        const entry = pathwayMap.get('map00010');

        expect(entry?.koNumbers).toEqual(['K00001']);
    });

    it('links reaction ids via reaction2pathway', () => {
        const entry = pathwayMap.get('map00010');

        expect(entry?.reactionIds).toEqual(['R00623']);
    });

    it('links compound ids via compound2pathway', () => {
        const entry = pathwayMap.get('map00010');

        expect(entry?.compoundIds).toEqual(['C00022']);
    });

    it('leaves the link fields empty when no link table references the pathway', () => {
        const entry = pathwayMap.get('map01100');

        expect(entry?.ecNumbers).toEqual([]);
        expect(entry?.koNumbers).toEqual([]);
        expect(entry?.reactionIds).toEqual([]);
        expect(entry?.compoundIds).toEqual([]);
    });

    it('builds the full entry for map00010', () => {
        expect(pathwayMap.get('map00010')).toEqual({
            name: 'Glycolysis / Gluconeogenesis',
            category: 'Metabolism',
            subCategory: 'Carbohydrate metabolism',
            ecNumbers: ['1.1.1.1', '2.7.1.1'],
            koNumbers: ['K00001'],
            reactionIds: ['R00623'],
            compoundIds: ['C00022'],
        });
    });

    it('builds the full entry for map01100 (no link table entries)', () => {
        expect(pathwayMap.get('map01100')).toEqual({
            name: 'Metabolic pathways',
            category: 'Metabolism',
            subCategory: 'Global and overview maps',
            ecNumbers: [],
            koNumbers: [],
            reactionIds: [],
            compoundIds: [],
        });
    });

    it('returns undefined for an unknown key', () => {
        expect(pathwayMap.get('map99999')).toBeUndefined();
    });
});
