import { describe, expect, it } from 'vitest';

// NodeInformation reaches into the KoMap singleton to expand a KO number into
// its EC numbers, so this file depends on the fixture the same way the mapping
// tests do: K00001 carries [EC:1.1.1.1] and K00844 carries [EC:2.7.1.1] in
// .fixture/ko, generated by globalSetup before this file is loaded.
import NodeInformation from '../../src/models/NodeInformation';

// Every field on NodeInformation is `private`, which in TypeScript is a
// compile-time rule and nothing more -- the fields are ordinary own properties
// at runtime and all five of them are serialised into the pathway response.
// Asserting on the JSON is therefore both the only way in from outside the
// class and the closest thing to the contract the frontend actually consumes.
const parse = (title: string) => JSON.parse(JSON.stringify(new NodeInformation(title)));

const empty = { ecNumbers: [], koNumbers: [], reactions: [], compounds: [], keggMaps: [] };

describe('NodeInformation title parsing', () => {
    it('records a KO number and expands the EC numbers KoMap has for it', () => {
        // The expansion is the only part of this class that reads another map,
        // and it is what puts an EC number on a node whose title never named
        // one. K00001 is `... [EC:1.1.1.1]` in the fixture.
        expect(parse('K00001')).toEqual({
            ...empty,
            koNumbers: [{ id: 'K00001', name: 'TODO' }],
            ecNumbers: [{ id: '1.1.1.1' }],
        });
    });

    it('still records a KO number that KoMap has never heard of, with no EC numbers', () => {
        // koMap.get() returns undefined here, so this exercises the `?.` and
        // the `?? []` on the expansion. A node titled with a KO number KEGG
        // added after the last data refresh must not blow up the request.
        expect(parse('K99999')).toEqual({
            ...empty,
            koNumbers: [{ id: 'K99999', name: 'TODO' }],
        });
    });

    it('records a compound id', () => {
        expect(parse('C00001')).toEqual({
            ...empty,
            compounds: [{ id: 'C00001', name: 'TODO' }],
        });
    });

    it('records a reaction id', () => {
        expect(parse('R00623')).toEqual({
            ...empty,
            reactions: [{ id: 'R00623' }],
        });
    });

    it('records a bare EC number, including one with a - wildcard component', () => {
        // ecRegex is the only anchored regex of the five, and it accepts `-`
        // for an unassigned component, which is how KEGG writes a partial
        // classification.
        expect(parse('1.1.1.1')).toEqual({ ...empty, ecNumbers: [{ id: '1.1.1.1' }] });
        expect(parse('1.1.1.-')).toEqual({ ...empty, ecNumbers: [{ id: '1.1.1.-' }] });
    });

    it('splits a title on commas and spaces and classifies every token', () => {
        // A real KEGG area title is a comma-separated list, and the map entry
        // within it is space-separated from what follows, which is why the
        // split is done twice.
        expect(parse('C00001 C00022, R00623, 2.7.1.1')).toEqual({
            ...empty,
            compounds: [{ id: 'C00001', name: 'TODO' }, { id: 'C00022', name: 'TODO' }],
            reactions: [{ id: 'R00623' }],
            ecNumbers: [{ id: '2.7.1.1' }],
        });
    });

    it('ignores tokens that match nothing, including the human-readable name', () => {
        // `E1.1.1.1` and `adh` are the enzyme name fields KEGG puts next to a
        // KO number; neither is an identifier and neither may be recorded as
        // one. `E1.1.1.1` in particular is what the anchoring on ecRegex buys.
        expect(parse('K00001, E1.1.1.1, adh')).toEqual({
            ...empty,
            koNumbers: [{ id: 'K00001', name: 'TODO' }],
            ecNumbers: [{ id: '1.1.1.1' }],
        });
    });

    it('yields empty lists for a title with no identifiers at all', () => {
        // The pathway fixture's areas are titled `Node A`/`Node B`/`Node C`,
        // so this is the case every existing pathway test already hits -- and,
        // until this file, the only one.
        expect(parse('Glycolysis')).toEqual(empty);
        expect(parse('')).toEqual(empty);
        expect(parse('   ')).toEqual(empty);
    });

    it('does not record the same EC number twice, however it was reached', () => {
        // addEcNumber is the one place that dedupes, and it has to: a KO
        // number expands to EC numbers that the title may also name outright.
        expect(parse('K00001 1.1.1.1')).toEqual({
            ...empty,
            koNumbers: [{ id: 'K00001', name: 'TODO' }],
            ecNumbers: [{ id: '1.1.1.1' }],
        });
    });
});

// The three tests below pin down behaviour that is surprising rather than
// intended. They are here so that a change to any of it is a visible decision
// in a diff instead of a silent shift in what the API returns -- not because
// the behaviour is worth keeping. See the PR that added this file.
describe('NodeInformation title parsing (current behaviour, not a guarantee)', () => {
    it('keeps the trailing colon in a map id, so the id does not match a PathwayMap key', () => {
        // mapRegex requires the colon (`map\d{5}:`) but the token, colon and
        // all, is what gets stored. PathwayMap is keyed `map00010`, so
        // `map00010:` looks up nothing. Note also that a map id *without* a
        // colon is not recognised at all.
        expect(parse('map00010: Glycolysis / Gluconeogenesis')).toEqual({
            ...empty,
            keggMaps: [{ id: 'map00010:', name: 'TODO' }],
        });
        expect(parse('map00010')).toEqual(empty);
    });

    it('stores the whole token, not the matched identifier, for the four unanchored regexes', () => {
        // koRegex and friends are unanchored, so a token that merely *contains*
        // an identifier is accepted -- and then recorded verbatim, punctuation
        // included. Neither id below exists in any map.
        expect(parse('(K00001)')).toEqual({ ...empty, koNumbers: [{ id: '(K00001)', name: 'TODO' }] });
        expect(parse('K000012345')).toEqual({ ...empty, koNumbers: [{ id: 'K000012345', name: 'TODO' }] });
    });

    it('deduplicates EC numbers but not KO numbers, compounds, reactions or maps', () => {
        // Only ecNumbers goes through addEcNumber; the other four branches push
        // unconditionally, so a repeated token is repeated in the response.
        expect(parse('K00001, K00001')).toEqual({
            ...empty,
            koNumbers: [{ id: 'K00001', name: 'TODO' }, { id: 'K00001', name: 'TODO' }],
            ecNumbers: [{ id: '1.1.1.1' }],
        });
    });
});
